version: "3.4"
services:

    redis:
        image: redis
        ports:
            - "3001:3001"

    publisher:
        build:
            context: .
            dockerfile: docker/publisher.Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - redis

    subscriber-console:
        build:
            context: .
            dockerfile: docker/subscriber.Dockerfile
        environment:
            - SUBSCRIBER=console
        depends_on:
            - publisher

    subscriber-all:
        build:
          context: .
          dockerfile: docker/subscriber.Dockerfile
        ports:
            - "3002:3002"
        environment:
            - SUBSCRIBER=all
        depends_on:
            - publisher

    subscriber-dy:
        build:
          context: .
          dockerfile: docker/subscriber.Dockerfile
        ports:
            - "3004:3004"
        environment:
            - SUBSCRIBER=dy
        depends_on:
            - publisher

    subscriber-sessionm:
        build:
          context: .
          dockerfile: docker/subscriber.Dockerfile
        ports:
            - "3005:3005"
        environment:
            - SUBSCRIBER=sessionm
        depends_on:
            - publisher

    subscriber-sitespect:
        build:
          context: .
          dockerfile: docker/subscriber.Dockerfile
        ports:
            - "3006:3006"
        environment:
            - SUBSCRIBER=sitespect
        depends_on:
            - publisher

    dashboard:
        build:
            context: .
            dockerfile: docker/dashboard.Dockerfile
        ports:
            - "3003:3003"
        depends_on:
            - subscriber-all
            - subscriber-dy
            - subscriber-sessionm
            - subscriber-sitespect
